######################################################################
# Automatically generated by qmake (2.01a) Fri Nov 12 00:44:37 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MotionPlan.h
SOURCES += Controller.cc main.cc Modul.cc MotionPlan.cc View.cc
